package com.nexus.backend.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

@Entity
@Table(name = "scenarios")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Scenario {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @Column(nullable = false)
    private String title;

    @Column(nullable = false, columnDefinition = "TEXT")
    private String description;

    @Column(name = "scenario_text", nullable = false, columnDefinition = "TEXT")
    private String scenarioText;

    @Column(nullable = false, length = 10)
    private String language;

    @Column(nullable = false, length = 20)
    private String difficulty;

    @Column(nullable = false, length = 50)
    private String category;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(nullable = false, columnDefinition = "jsonb")
    private List<String> roles;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "required_terminology", nullable = false, columnDefinition = "jsonb")
    private List<String> requiredTerminology;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "project_ids", nullable = false, columnDefinition = "jsonb")
    private List<UUID> projectIds;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "schedule_ids", nullable = false, columnDefinition = "jsonb")
    private List<UUID> scheduleIds;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "document_ids", nullable = false, columnDefinition = "jsonb")
    private List<UUID> documentIds;

    @Column(name = "auto_generated", nullable = false)
    @Builder.Default
    private Boolean autoGenerated = false;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;
}
