-- V12: Placeholder for deleted migration
--
-- This migration was created and later made obsolete during development.
-- Keeping this placeholder to maintain migration version sequence for team collaboration.
--
-- Original purpose: Dropped email_embeddings table (migrated to Qdrant)
-- Current status: Empty placeholder to prevent Flyway validation errors
--
-- Note: This avoids pgvector-related migration issues for new team members
--
-- DO NOTHING (intentionally empty)
